version: "3.9"
services:
  db:
    image: postgres
    restart: on-failure
    container_name: postgres_cli_Mail
    environment:
        POSTGRES_USER: MeAndOnlyMe
        POSTGRES_PASSWORD: MyAwesomePasswordIsHardToRemember
        POSTGRES_DB: subjects
        POSTGRES_HOST_AUTH_METHOD: password
    ports: 
        - 5432:5432

  adminer:
    container_name: adminer_cli_Mail
    image: adminer:4.7.7
    restart: on-failure
    ports:
      - 8080:8080